name: my_apps
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.8
  intl: ^0.19.0

  cupertino_icons: ^1.0.2
  numberpicker: ^2.1.2
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  firebase_database: ^11.0.1
  cloud_firestore: ^5.0.1
  uuid: ^4.4.0
  connectivity_plus: ^6.0.3
  network_info_plus: ^5.0.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/ikan1.png"

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/akuarium.png
    - lib/assets/images/Centang.png
    - lib/assets/images/ikan1.png
    - lib/assets/images/ikan2.png
    - lib/assets/images/jadwal.png
    - lib/assets/images/jam.png
    - lib/assets/images/kolambesar.png
    - lib/assets/images/kolamkecil.png
    - lib/assets/images/Logo.png
    - lib/assets/images/LogoAwal.png
    - lib/assets/images/pulauindo.png
