// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4rMIQ9ur3yOOBZkST5Efi251LXkD-LN8',
    appId: '1:394768677488:web:927182e0bd98e74c85d2b5',
    messagingSenderId: '394768677488',
    projectId: 'fishylicious-62a5b',
    authDomain: 'fishylicious-62a5b.firebaseapp.com',
    storageBucket: 'fishylicious-62a5b.appspot.com',
    measurementId: 'G-64EH5W8FF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEyUGso1G8n7NKtlHLen9FRqTJpCRbs44',
    appId: '1:394768677488:android:fd46850651ce874585d2b5',
    databaseURL:
        'https://fishylicious-62a5b-default-rtdb.asia-southeast1.firebasedatabase.app/',
    messagingSenderId: '394768677488',
    projectId: 'fishylicious-62a5b',
    storageBucket: 'fishylicious-62a5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5L42CfiUejJHRdEE5__rNjS-u5kGuXkw',
    appId: '1:394768677488:ios:703f6ddb4dd720f085d2b5',
    messagingSenderId: '394768677488',
    projectId: 'fishylicious-62a5b',
    storageBucket: 'fishylicious-62a5b.appspot.com',
    iosBundleId: 'com.example.myApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5L42CfiUejJHRdEE5__rNjS-u5kGuXkw',
    appId: '1:394768677488:ios:703f6ddb4dd720f085d2b5',
    messagingSenderId: '394768677488',
    projectId: 'fishylicious-62a5b',
    storageBucket: 'fishylicious-62a5b.appspot.com',
    iosBundleId: 'com.example.myApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4rMIQ9ur3yOOBZkST5Efi251LXkD-LN8',
    appId: '1:394768677488:web:6aafcbcf0f28508385d2b5',
    messagingSenderId: '394768677488',
    projectId: 'fishylicious-62a5b',
    authDomain: 'fishylicious-62a5b.firebaseapp.com',
    storageBucket: 'fishylicious-62a5b.appspot.com',
    measurementId: 'G-3CHWEVH8BM',
  );
}
